set_property PACKAGE_PIN R2 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports f_out]
set_property IOSTANDARD LVCMOS33 [get_ports f_crys]
set_property PACKAGE_PIN U16 [get_ports f_out]
set_property PACKAGE_PIN W5 [get_ports f_crys]
