set_property PACKAGE_PIN V19 [get_ports {b[3]}]
set_property PACKAGE_PIN U19 [get_ports {b[2]}]
set_property PACKAGE_PIN E19 [get_ports {b[1]}]
set_property PACKAGE_PIN U16 [get_ports {b[0]}]
set_property PACKAGE_PIN R2 [get_ports rst]

set_property IOSTANDARD LVCMOS33 [get_ports {b[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {b[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {b[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {b[0]}]
set_property PACKAGE_PIN W5 [get_ports f_crys]
set_property IOSTANDARD LVCMOS33 [get_ports f_crys]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports f_out]
set_property PACKAGE_PIN L1 [get_ports f_out]
